"""Tests for the model-facing projections in `spice_mcp_app.compact`.

The projections exist to cut input tokens, so the danger they carry is obvious: a
projection that drops something the model needed buys a smaller number and a worse answer.
These tests are therefore written from that direction - they assert what **survives**, ref
by ref and node by node, and only then that the noise is gone.

`RCLP_NETLIST` and `SOURCE_CONFLICT_SIM` are **real captured output**, lifted from
`bench/baseline-session-32589a49.json` and from a `run_simulation` on
`fixtures/source_conflict.asc`. Invented samples would be the wrong thing to test against:
these payloads are the reason the projection is worth doing, and LTspice's log messages in
particular are inconsistent enough that a plausible-looking fake would test a shape the
tool never emits.
"""

from __future__ import annotations

import json

from spice_mcp_app.compact import (
    MAX_RAW_TAIL,
    circuit_summary,
    compact_tool_result,
    sim_summary,
    static_summary,
)

# --- real captured payloads ------------------------------------------------------------

# `read_netlist` on RCLP.asc, verbatim from the baseline session log. The staging paths are
# what they were on that run; they are here because removing them is the point.
RCLP_NETLIST: dict = {
    "source_path": "C:\\Users\\Expertician\\ClaudeCodeTest\\SpiceMCP\\RCLP.asc",
    "netlist_path": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\RCLP_9a651a72db30\\RCLP.net",
    "title": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\RCLP_9a651a72db30\\RCLP.asc",
    "components": [
        {
            "ref": "V1", "prefix": "V", "kind": "voltage source",
            "nodes": ["Vin", "0"], "value": "AC 0.7 3000",
            "line_no": 3, "raw_line": "V1 Vin 0 AC 0.7 3000", "nodes_uncertain": False,
        },
        {
            "ref": "C1", "prefix": "C", "kind": "capacitor",
            "nodes": ["Vout", "0"], "value": "6.63n",
            "line_no": 4, "raw_line": "C1 Vout 0 6.63n", "nodes_uncertain": False,
        },
        {
            "ref": "R2", "prefix": "R", "kind": "resistor",
            "nodes": ["Vout", "0"], "value": "15k",
            "line_no": 5, "raw_line": "R2 Vout 0 15k", "nodes_uncertain": False,
        },
        {
            "ref": "R1", "prefix": "R", "kind": "resistor",
            "nodes": ["Vout", "NC_01"], "value": "10k",
            "line_no": 6, "raw_line": "R1 Vout NC_01 10k", "nodes_uncertain": False,
        },
    ],
    "directives": [
        {"kind": ".ac", "text": ".ac dec 10 1k 100k", "line_no": 7},
        {"kind": ".backanno", "text": ".backanno", "line_no": 8},
    ],
    "subcircuits": [],
    "nets": [
        {"name": "0", "connection_count": 3, "connected_refs": ["C1", "R2", "V1"]},
        {"name": "NC_01", "connection_count": 1, "connected_refs": ["R1"]},
        {"name": "Vin", "connection_count": 1, "connected_refs": ["V1"]},
        {"name": "Vout", "connection_count": 3, "connected_refs": ["C1", "R1", "R2"]},
    ],
    "raw_text": (
        "* C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\RCLP_9a651a72db30\\RCLP.asc\n"
        "* Generated by LTspice 26.0.2 for Windows.\n"
        "V1 Vin 0 AC 0.7 3000\nC1 Vout 0 6.63n\nR2 Vout 0 15k\nR1 Vout NC_01 10k\n"
        ".ac dec 10 1k 100k\n.backanno\n.end\n"
    ),
}

RCLP_STATIC: dict = {
    "source_path": "C:\\Users\\Expertician\\ClaudeCodeTest\\SpiceMCP\\RCLP.asc",
    "ok": False,
    "findings": [
        {
            "check": "floating_net", "severity": "error",
            "message": "Net 'Vin' has only one connection (V1), so no current can flow "
                       "through it.",
            "refs": ["V1"], "nets": ["Vin"], "line_no": None,
            "suggestion": "Either connect 'Vin' to the rest of the circuit or remove V1.",
        },
        {
            "check": "floating_pin", "severity": "error",
            "message": "R1 has an unconnected pin. LTspice auto-named it 'NC_01'.",
            "refs": ["R1"], "nets": ["NC_01"], "line_no": 6,
            "suggestion": "Wire the dangling pin of R1 to the node it belongs to.",
        },
    ],
    "summary": "Found 2 errors without running a simulation.",
}

# A genuinely failed run: `source_conflict.asc` is statically clean and does not solve.
# The fatal line carries no `ERROR:` prefix, which is exactly why the raw tail is kept.
SOURCE_CONFLICT_SIM: dict = {
    "circuit_path": "C:\\repo\\fixtures\\source_conflict.asc",
    "simulated_path": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\sc_1\\source_conflict.asc",
    "succeeded": False,
    "timed_out": False,
    "returncode": 0,
    "log_path": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\sc_1\\source_conflict.log",
    "raw_path": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\sc_1\\source_conflict.raw",
    "log": {
        "log_path": "C:\\Users\\Expertician\\AppData\\Local\\Temp\\spice_mcp_work\\sc_1\\source_conflict.log",
        "ltspice_version": "LTspice 26.0.2 for Windows",
        "circuit": "source_conflict.asc",
        "succeeded": False,
        "elapsed_s": 0.031,
        "solver": "Normal",
        "method": "trap",
        "findings": [
            {
                "check": "over_defined_matrix", "severity": "error",
                "message": "Over-defined matrix: two voltage sources share a node.",
                "refs": [], "nets": [], "line_no": None, "suggestion": None,
            },
        ],
        "measurements": [],
        "step_count": 0,
        "files_loaded": ["C:\\Program Files\\LTC\\standard.res"],
        "summary": "The simulation failed: over-defined matrix.",
        "raw_text": "Circuit: * source_conflict.asc\n\nOver-defined matrix.\n"
                    "Iteration No. 1\nDate: Sat Aug 30 12:00:00 2026\n",
    },
    "summary": "The simulation failed: over-defined matrix.",
}


# --- what must survive ------------------------------------------------------------------


def test_the_summary_keeps_every_ref_node_value_and_directive():
    summary = circuit_summary(RCLP_NETLIST)

    for ref in ("V1", "C1", "R2", "R1"):
        assert ref in summary
    # NC_01 is the whole diagnosis for this circuit. Vin/Vout/0 are how the model knows
    # what is connected to what.
    for node in ("NC_01", "Vin", "Vout", "0"):
        assert node in summary
    for value in ("AC 0.7 3000", "6.63n", "15k", "10k"):
        assert value in summary
    assert ".ac dec 10 1k 100k" in summary
    assert ".backanno" in summary


def test_nodes_stay_in_pin_order():
    """`R1 Vout NC_01` and `R1 NC_01 Vout` are different circuits to a reader.

    Reordering would not lose information in a two-terminal passive, but it would in
    anything polarised, and a projection that is only order-safe for resistors is not one
    to build a diagnosis on.
    """
    summary = circuit_summary(RCLP_NETLIST)
    assert "R1 Vout NC_01 10k" in summary
    assert "V1 Vin 0 AC 0.7 3000" in summary


def test_a_floating_net_is_visible_without_the_connection_count():
    """`connection_count` is dropped, so the one-ref net has to read as one on its own."""
    summary = circuit_summary(RCLP_NETLIST)
    assert "NC_01: R1" in summary
    assert "Vin: V1" in summary
    assert "Vout: C1, R1, R2" in summary


def test_an_uncertain_pin_count_is_surfaced_not_dropped():
    """The server downgrades its own connectivity checks on this flag.

    If the projection dropped it, the model would be free to assert a floating net from a
    node list the server had already decided it could not trust.
    """
    payload = json.loads(json.dumps(RCLP_NETLIST))
    payload["components"][3]["nodes_uncertain"] = True
    summary = circuit_summary(payload)
    assert "R1" in summary
    assert "could not be determined" in summary


def test_subcircuit_ports_survive():
    payload = json.loads(json.dumps(RCLP_NETLIST))
    payload["subcircuits"] = [{"name": "opamp", "ports": ["in+", "in-", "out"], "line_no": 9}]
    summary = circuit_summary(payload)
    assert ".subckt opamp in+ in- out" in summary


# --- what must go -----------------------------------------------------------------------


def test_the_summary_drops_paths_and_the_duplicate_raw_text():
    summary = circuit_summary(RCLP_NETLIST)

    # Staging paths. Two thirds of the original payload's bulk, and quoting one back at the
    # user would name a file that no longer exists.
    assert "Temp" not in summary
    assert "spice_mcp_work" not in summary
    assert "netlist_path" not in summary
    assert "source_path" not in summary
    # `raw_text` re-states the components line for line.
    assert "Generated by LTspice" not in summary
    assert ".end" not in summary
    # Per-component bookkeeping.
    assert "raw_line" not in summary
    assert "line_no" not in summary
    assert "voltage source" not in summary
    assert "connection_count" not in summary


def test_the_summary_is_a_fraction_of_the_payload_it_replaces():
    """The measurement the whole optimisation rests on, asserted rather than claimed."""
    full = json.dumps(RCLP_NETLIST, indent=2, ensure_ascii=False)
    summary = circuit_summary(RCLP_NETLIST)
    assert len(summary) < len(full) * 0.25, (len(summary), len(full))


# --- the other three tools --------------------------------------------------------------


def test_static_findings_survive_and_the_path_does_not():
    summary = static_summary(RCLP_STATIC)
    assert "Found 2 errors" in summary
    assert "floating_net" in summary and "floating_pin" in summary
    assert "NC_01" in summary and "Vin" in summary
    # The suggestion is the fix the user acts on.
    assert "Wire the dangling pin of R1" in summary
    assert "ClaudeCodeTest" not in summary


def test_a_clean_static_result_says_so_explicitly():
    """An empty findings list must not project to a bare summary line the model can misread."""
    summary = static_summary({"source_path": "x", "ok": True, "findings": [], "summary": "Clean."})
    assert "no findings" in summary


def test_a_failed_simulation_keeps_the_raw_log_tail():
    """Of five distinct LTspice failures only two carry an `ERROR:` prefix.

    So for an unclassified fatal message the raw text is the only place the reason exists,
    and dropping it on a failed run would be removing grounding to win the metric.
    """
    summary = sim_summary(SOURCE_CONFLICT_SIM)
    assert "simulation succeeded: False" in summary
    assert "over_defined_matrix" in summary
    assert "Over-defined matrix." in summary
    # But not the exit code the model is told not to trust, nor the staging paths.
    assert "returncode" not in summary
    assert "spice_mcp_work" not in summary
    assert "standard.res" not in summary


def test_a_successful_simulation_drops_the_boilerplate_log():
    payload = json.loads(json.dumps(SOURCE_CONFLICT_SIM))
    payload["succeeded"] = True
    payload["log"]["succeeded"] = True
    payload["log"]["findings"] = []
    payload["log"]["raw_text"] = "Circuit: x\n\nDirect Newton iteration succeeded.\n" * 40
    payload["log"]["summary"] = "The simulation completed."
    summary = sim_summary(payload)
    assert "simulation succeeded: True" in summary
    assert "Direct Newton" not in summary


def test_a_long_failed_log_is_capped_from_the_tail():
    """The banner is at the top of an LTspice log and the diagnosis is at the bottom."""
    payload = json.loads(json.dumps(SOURCE_CONFLICT_SIM))
    payload["log"]["raw_text"] = ("filler line\n" * 2000) + "Fatal error at the very end.\n"
    summary = sim_summary(payload)
    assert "Fatal error at the very end." in summary
    assert "[earlier log output omitted]" in summary
    assert len(summary) < MAX_RAW_TAIL + 2000


def test_measurements_survive():
    payload = json.loads(json.dumps(SOURCE_CONFLICT_SIM))
    payload["succeeded"] = True
    payload["log"]["succeeded"] = True
    payload["log"]["measurements"] = [{"name": "fc", "value": "(-3.01dB,-45 deg)"}]
    summary = sim_summary(payload)
    assert "fc = (-3.01dB,-45 deg)" in summary


# --- the dispatcher, and its fail-open contract -----------------------------------------


def test_the_dispatcher_projects_the_four_read_tools():
    for name, payload in (
        ("read_netlist", RCLP_NETLIST),
        ("check_netlist_static", RCLP_STATIC),
        ("run_simulation", SOURCE_CONFLICT_SIM),
        ("read_sim_log", SOURCE_CONFLICT_SIM["log"]),
    ):
        projected = compact_tool_result(name, json.dumps(payload, indent=2))
        assert projected, name
        assert len(projected) < len(json.dumps(payload, indent=2))


def test_the_write_tools_pass_through_untouched():
    """`patch_component_value` in particular: `api._pending_patch` parses this JSON to
    drive the Apply button, so compacting it would break the approval flow rather than
    merely shrink a payload."""
    patch = json.dumps({"asc_path": "x.asc", "ref": "C1", "new_value": "100n", "diff": "..."})
    assert compact_tool_result("patch_component_value", patch) is None
    assert compact_tool_result("diff_netlist", "{}") is None
    assert compact_tool_result("export_netlist", "{}") is None


def test_an_error_result_reaches_the_model_verbatim():
    """Error text is prose, not JSON - and it is often the actual diagnosis.

    The approval gate's own refusal travels this path too.
    """
    refusal = "REFUSED: writing to the schematic needs the user's approval first."
    assert compact_tool_result("patch_component_value", refusal) is None
    assert compact_tool_result("read_netlist", "Tool read_netlist failed: no such file") is None


def test_an_unexpected_shape_fails_open():
    """`None` means "send it unchanged". Losing a real result to a projection bug would be
    worse than paying for the full text, so every case this cannot handle returns `None`."""
    assert compact_tool_result("read_netlist", "[]") is None
    assert compact_tool_result("read_netlist", '{"something": "else"}') is None
    assert compact_tool_result("run_simulation", '{"no_succeeded_key": true}') is None
    assert compact_tool_result("unknown_tool", json.dumps(RCLP_NETLIST)) is None


def test_circuit_summary_fails_closed_on_a_non_netlist():
    """The opposite direction from the dispatcher, and deliberately so.

    `api._selection_note` uses this return value to decide whether to tell the model the
    topology is already loaded. Rendering something from the wrong payload would put a
    false claim in the model's context, which is the one way this optimisation could turn
    into a hallucination.
    """
    assert circuit_summary(RCLP_STATIC) is None
    assert circuit_summary({}) is None
    assert circuit_summary({"components": [], "nets": []}) is None
